DROP TABLE TEMPORAL;

CREATE TABLE TEMPORAL (
    NAME VARCHAR2(50 BYTE) NOT NULL,
    INFOR VARCHAR2(100 BYTE) NOT NULL
);

CREATE OR REPLACE PROCEDURE CALEMPLE(NUMEMP NUMBER)
IS
  VSALARY EMPLOYEE.SALARY%TYPE;
  VACTUALIZA EMPLOYEE.SALARY%TYPE;
  VNAME EMPLOYEE.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME, SALARY INTO VNAME, VSALARY FROM EMPLOYEE WHERE EMPLOYEE_ID = NUMEMP;
    IF VSALARY <= 1000 THEN
        VACTUALIZA := VSALARY + (VSALARY * 20 /100);
        UPDATE EMPLOYEE SET SALARY = VACTUALIZA WHERE EMPLOYEE_ID = NUMEMP;
        INSERT INTO TEMPORAL VALUES(VNAME,'Sueldo actualizado');
    ELSE
        INSERT INTO TEMPORAL VALUES(VNAME,'No necesita actualización');
    END IF;
END;
/

EXECUTE CALEMPLE(7499);

SELECT * FROM TEMPORAL;