DROP TABLE TEMPORAL;

CREATE TABLE TEMPORAL(
    PRODUCTID NUMBER(6,0) NOT NULL,
    INFOR VARCHAR2(80 BYTE) NOT NULL
);

DECLARE
		VTOD_PED sales_order.total%TYPE;
        VPRODUCTID item.product_id%TYPE;
		CURSOR C1 IS  SELECT so.total, it.product_id FROM CUSTOMER CU, SALES_ORDER SO, ITEM IT WHERE CU.CUSTOMER_ID = SO.CUSTOMER_ID AND SO.ORDER_ID = IT.ORDER_ID AND CU.CUSTOMER_ID = 101;
BEGIN
    OPEN C1;
    LOOP 
        FETCH C1 INTO VTOD_PED,VPRODUCTID;
        EXIT WHEN C1%NOTFOUND;
        VTOD_PED := VTOD_PED + 10;
        INSERT INTO TEMPORAL VALUES(VPRODUCTID,'Diez unidades más vendidas');
    END LOOP;
    CLOSE C1;
   
END;
/

SELECT * FROM TEMPORAL;